---

workspace:
  base: /go
  path: src/github.com/packethost/pkg

pipeline:
  lint:
    group: ci
    image: golangci/golangci-lint:v1.23.1
    commands:
      - golangci-lint run -v --modules-download-mode vendor
      - gofmt -d *.go | (! grep '.')

  test:
    group: ci
    image: golang:1.13.1
    commands:
      - GO111MODULE=on go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

  build:
    group: ci
    image: golang:1.13.1-alpine3.10
    commands:
      - GO111MODULE=on CGO_ENABLED=0 go build -mod=vendor ./cmd/...

  examplelog:
    group: examples
    image: alpine
    commands:
      - ./examplelog
    environment:
      PACKET_ENV: ci
      PACKET_VERSION: "0"
    secrets: [rollbar_token]

  codecov:
    group: notifications
    image: plugins/codecov
    secrets: [codecov_token]
