---

workspace:
  base: /go
  path: src/github.com/packethost/pkg

pipeline:
  lint:
    group: ci
    image: golang:1.10-alpine
    commands:
      - apk add --update --upgrade --no-cache git
      - go get -v -u github.com/alecthomas/gometalinter
      - gometalinter --install
      - gometalinter --errors --vendor --vendored-linters ./...
      - gofmt -d *.go | (! grep '.')

  test:
    group: ci
    image: golang:1.11.1
    commands:
      - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

  codecov:
    group: notifications
    image: plugins/codecov
    secrets: [codecov_token]
